"""Canonical broker contracts and Paper-safe adapter foundations."""

from .account import AccountSnapshot, LiquidationFact, PositionFact, PositionSide
from .capabilities import PORT_NAMES, CapabilityDescriptor
from .conformance import ConformanceReport, EvidenceKind, run_paper_conformance
from .errors import BrokerCapabilityError, BrokerError, PaperBoundaryError, RuntimeBoundaryError
from .fees import (
    FeeEvent,
    FeeKind,
    FeeScheduleSnapshot,
    FeeSource,
    FeeState,
    FillFact,
    FundingPayment,
)
from .host import (
    BrokerRegistry,
    BrokerSelection,
    HostBrokerBinding,
    HostRole,
    HostSafetyPolicy,
    RecordingEvent,
    RecordingTrack,
)
from .models import (
    AccountScope,
    BrokerEnvironment,
    BrokerIdentity,
    Provenance,
    SignerKind,
)
from .orders import (
    OrderFill,
    OrderIntent,
    OrderReceipt,
    OrderSide,
    OrderState,
    OrderType,
    TimeInForce,
)
from .paper import (
    InMemoryPaperTransport,
    PaperBrokerAdapter,
    PaperPreflight,
    PaperReceipt,
)
from .ports import (
    AccountPort,
    FeePort,
    InstrumentPort,
    MarketDataPort,
    OrderExecutionPort,
    ProtectionOrderPort,
)
from .protection import (
    ProtectionExecution,
    ProtectionGroup,
    ProtectionLeg,
    ProtectionQuantityPolicy,
    ProtectionType,
    TriggerReference,
)
from .runtime import (
    AccountReference,
    BrokerRuntimeSession,
    ExternalEnvironmentApproval,
    RuntimeActivationPolicy,
    RuntimeOperationGuard,
    RuntimePreflight,
    SignerReference,
    SignerProvider,
    preflight_runtime_session,
)
from .security import find_secret_like_literals

__all__ = [
    "PORT_NAMES",
    "AccountPort",
    "AccountScope",
    "AccountSnapshot",
    "BrokerCapabilityError",
    "BrokerEnvironment",
    "BrokerError",
    "BrokerIdentity",
    "BrokerRegistry",
    "BrokerSelection",
    "CapabilityDescriptor",
    "ConformanceReport",
    "EvidenceKind",
    "FeeEvent",
    "FeeKind",
    "FeePort",
    "FeeScheduleSnapshot",
    "FeeSource",
    "FeeState",
    "FillFact",
    "FundingPayment",
    "HostBrokerBinding",
    "HostRole",
    "HostSafetyPolicy",
    "InMemoryPaperTransport",
    "InstrumentPort",
    "LiquidationFact",
    "MarketDataPort",
    "OrderExecutionPort",
    "OrderFill",
    "OrderIntent",
    "OrderReceipt",
    "OrderSide",
    "OrderState",
    "OrderType",
    "PaperBoundaryError",
    "PaperBrokerAdapter",
    "PaperPreflight",
    "PaperReceipt",
    "PositionFact",
    "PositionSide",
    "ProtectionExecution",
    "ProtectionGroup",
    "ProtectionLeg",
    "ProtectionOrderPort",
    "ProtectionQuantityPolicy",
    "ProtectionType",
    "Provenance",
    "AccountReference",
    "BrokerRuntimeSession",
    "ExternalEnvironmentApproval",
    "RuntimeActivationPolicy",
    "RuntimeBoundaryError",
    "RuntimeOperationGuard",
    "RuntimePreflight",
    "RecordingEvent",
    "RecordingTrack",
    "SignerKind",
    "SignerProvider",
    "SignerReference",
    "TimeInForce",
    "TriggerReference",
    "find_secret_like_literals",
    "run_paper_conformance",
    "preflight_runtime_session",
]
