"""Canonical broker contracts and Paper-safe adapter foundations."""

from .account import AccountSnapshot, LiquidationFact, PositionFact, PositionSide
from .capabilities import PORT_NAMES, CapabilityDescriptor
from .conformance import ConformanceReport, EvidenceKind, run_paper_conformance
from .errors import (
    BrokerCapabilityError,
    BrokerError,
    MarketDataGateError,
    OrderIdempotencyError,
    PaperBoundaryError,
    RuntimeBoundaryError,
)
from .evidence import (
    EVIDENCE_IDENTITY_FIELDS,
    EvidenceClass,
    EvidenceIdentity,
    ReconciliationEvidence,
    RuntimeReadinessReport,
    run_paper_runtime_readiness,
)
from .fees import (
    FeeEvent,
    FeeKind,
    FeeScheduleSnapshot,
    FeeSource,
    FeeState,
    FillFact,
    FundingPayment,
)
from .host import (
    BrokerRegistry,
    BrokerSelection,
    CanonicalAdapterReceipt,
    CanonicalBrokerHost,
    CanonicalHostRequest,
    CanonicalHostReceipt,
    CanonicalPortQuery,
    HostBrokerBinding,
    HostRole,
    HostSafetyPolicy,
    RecordingEvent,
    RecordingTrack,
)
from .models import (
    AccountScope,
    BrokerEnvironment,
    BrokerIdentity,
    Provenance,
    SignerKind,
)
from .orders import (
    OrderFill,
    OrderIntent,
    OrderReceipt,
    OrderSide,
    OrderState,
    OrderType,
    SlippagePolicy,
    TimeInForce,
)
from .paper import (
    InMemoryPaperTransport,
    PaperBrokerAdapter,
    PaperPreflight,
    PaperReceipt,
)
from .ports import (
    AccountPort,
    FeePort,
    InstrumentPort,
    MarketDataPort,
    OrderExecutionPort,
    ProtectionOrderPort,
)
from .protection import (
    ProtectionExecution,
    ProtectionGroup,
    ProtectionLeg,
    ProtectionLifecycleState,
    ProtectionLifecycleStatus,
    ProtectionQuantityPolicy,
    ProtectionReceipt,
    ProtectionRetryPlan,
    ProtectionType,
    TriggerReference,
)
from .runtime import (
    AccountReference,
    BrokerRuntimeSession,
    ExternalEnvironmentApproval,
    RuntimeActivationPolicy,
    RuntimeOperationGuard,
    RuntimePreflight,
    SignerReference,
    SignerProvider,
    preflight_runtime_session,
)
from .runtime_facts import RuntimeFactLedger
from .security import find_secret_like_literals

__all__ = [
    "PORT_NAMES",
    "AccountPort",
    "AccountScope",
    "AccountSnapshot",
    "BrokerCapabilityError",
    "BrokerEnvironment",
    "BrokerError",
    "BrokerIdentity",
    "BrokerRegistry",
    "BrokerSelection",
    "CanonicalAdapterReceipt",
    "CanonicalBrokerHost",
    "CanonicalHostRequest",
    "CanonicalHostReceipt",
    "CanonicalPortQuery",
    "CapabilityDescriptor",
    "ConformanceReport",
    "EvidenceClass",
    "EvidenceIdentity",
    "EVIDENCE_IDENTITY_FIELDS",
    "EvidenceKind",
    "FeeEvent",
    "FeeKind",
    "FeePort",
    "FeeScheduleSnapshot",
    "FeeSource",
    "FeeState",
    "FillFact",
    "FundingPayment",
    "HostBrokerBinding",
    "HostRole",
    "HostSafetyPolicy",
    "InMemoryPaperTransport",
    "InstrumentPort",
    "LiquidationFact",
    "MarketDataPort",
    "MarketDataGateError",
    "OrderExecutionPort",
    "OrderIdempotencyError",
    "OrderFill",
    "OrderIntent",
    "OrderReceipt",
    "OrderSide",
    "OrderState",
    "OrderType",
    "SlippagePolicy",
    "PaperBoundaryError",
    "PaperBrokerAdapter",
    "PaperPreflight",
    "PaperReceipt",
    "PositionFact",
    "PositionSide",
    "ProtectionExecution",
    "ProtectionGroup",
    "ProtectionLeg",
    "ProtectionLifecycleState",
    "ProtectionLifecycleStatus",
    "ProtectionOrderPort",
    "ProtectionQuantityPolicy",
    "ProtectionReceipt",
    "ProtectionRetryPlan",
    "ProtectionType",
    "Provenance",
    "AccountReference",
    "BrokerRuntimeSession",
    "ExternalEnvironmentApproval",
    "RuntimeActivationPolicy",
    "RuntimeBoundaryError",
    "RuntimeOperationGuard",
    "RuntimePreflight",
    "RuntimeFactLedger",
    "RuntimeReadinessReport",
    "ReconciliationEvidence",
    "RecordingEvent",
    "RecordingTrack",
    "SignerKind",
    "SignerProvider",
    "SignerReference",
    "TimeInForce",
    "TriggerReference",
    "find_secret_like_literals",
    "run_paper_conformance",
    "preflight_runtime_session",
    "run_paper_runtime_readiness",
]
